Repository shorebirdtech/shorebird, pull requests merged in 2025-01, with the labels that each got.

#2486 ci(e2e): fix e2e and add recent Flutter versions
  .github/workflows/e2e.yaml
  cspell.config.yaml
  scripts/patch_e2e.sh
Labels: ci

#2646 fix(shorebird_cli): "SYS_KEYS has no physical keys" during preview
  cspell.config.yaml
  packages/shorebird_cli/lib/src/executables/adb.dart
  packages/shorebird_cli/test/src/executables/adb_test.dart
Labels: bug

#2774 feat(shorebird_cli): `shorebird patch` should only list releases for specified platform
  packages/shorebird_cli/lib/src/commands/patch/patch_command.dart
  packages/shorebird_cli/test/src/commands/patch/patch_command_test.dart
Labels: enhancement

#2777 chore(shorebird_cli): improve error message when Flutter project does not support macOS
  packages/shorebird_cli/lib/src/validators/macos_network_entitlement_validator.dart
  packages/shorebird_cli/test/src/validators/macos_network_entitlement_validator_test.dart
Labels: bug

#2781 feat(shorebird_cli): `shorebird preview` should filter releases by platform
  packages/shorebird_cli/lib/src/commands/preview_command.dart
  packages/shorebird_cli/test/src/commands/preview_command_test.dart
Labels: enhancement
